---
services: docker

env:
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: ""
  - distro: fedora24
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: ""
  - distro: ubuntu1204
    init: /sbin/init
    run_opts: "--privileged"
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  # Pull container.
  - 'docker pull dmanto/docker-${distro}-ansible-plenv-and-carton:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run -d -v "${PWD}":/etc/ansible/roles/role_under_test ${run_opts} dmanto/docker-${distro}-ansible-plenv-and-carton:latest "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Ensure cpanm is installed.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c "which cpanm"'

  # Ensure DBD::Oracle is installed.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c "perl -MDBD::Oracle e 1"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/