---
- name: install dependencies package - Debian
  package: name={{ item }} state=latest
  become: yes
  with_items:
    - alien
    - libaio1

- name: install rmps with alien package
  shell: "alien -i {{ role_path }}/files/oracle/*.rpm"
  args:
    creates: /usr/lib/oracle/12.1/client64/bin/sqlplus
  become: yes
