---
- name: install dependencies package - Debian
  apt: name={{ item }} update_cache=yes
  become: yes
  with_items:
    - alien
    - libaio1
    - sudo

- name: install rmps with alien package
  shell: "alien -i {{ role_path }}/files/oracle/*.rpm"
  args:
    creates: /usr/lib/oracle/12.1/client64/bin/sqlplus
  become: yes

- name: Installs cpanm
  apt: name=cpanm state=latest
  when: cpanm_installed.stdout == ''
