- name: install dependencies package - Debian
  package: name={{ item }} state=latest
  become: yes
  with_items:
    - alien
    - libaio1
    - sudo

- name: install rmps with alien package
  shell: >
    alien -i rpm_0 &&
    alien -i rpm_1 &&
    alien -i rpm_2
  args:
    creates: /usr/lib/oracle/12.1/client64/bin/1-sqlplus
