- name: install dependencies package - Debian
  package: name={{ item }} state=latest
  become: yes
  with_items:
    - alien
    - libaio1
    - sudo

- name: install rmps with alien package
  shell: >
    alien -i oracle/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm &&
    alien -i oracle/oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm &&
    alien -i oracle/oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm
  args:
    creates: /usr/lib/oracle/12.1/client64/bin/1-sqlplus
