- name: install dependencies package - Debian
  package: name={{ item }} state=latest
  become: yes
  with_items:
    - alien
    - libaio1
    - sudo

- name: install rmps with alien package
  shell: >
    alien -i {{ oracle_files[0].path }} &&
    alien -i {{ oracle_files[1].path }} &&
    alien -i {{ oracle_files[2].path }}
  args:
    creates: /usr/lib/oracle/12.1/client64/bin/sqlplus