---
- name: Check if cpanm is installed
  shell: ~/.plenv/bin/plenv which cpanm
  ignore_errors: yes
  register: cpanm_installed
  become: yes
  become_user: "{{ app_user }}"
  changed_when: false

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'

- include: "{{role_path}}/tasks/redhat.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- include: "{{role_path}}/tasks/fedora.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Check if DBD::Oracle is installed
  shell: ~/.plenv/bin/plenv exec perl -MDBD::Oracle -E say '1'
  ignore_errors: yes
  register: dbd_oracle_installed
  become: yes
  become_user: "{{ app_user }}"
  changed_when: false

- debug:
    var: dbd_oracle_installed

- name: Installs DBD::Oracle
  shell:
    cmd: |
      cd
      ~/.plenv/bin/plenv exec cpanm DBI
      ~/.plenv/bin/plenv exec cpanm --look DBD::Oracle <<FINAL
      perl Makefile.PL -l
      make
      make test
      make install
      exit
      FINAL
  become: yes
  become_user: "{{ app_user }}"
  environment:
    - ORACLE_HOME: /usr/lib/oracle/12.1/client64
    - LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
  when: dbd_oracle_installed.stdout != '1'
  