---
- find:
    paths: "{{ role_path }}/files/oracle"
    patterns: "*.rpm"
  register: oracle_files

- include: "{{role_path}}/tasks/redhat.yml"
  when: ansible_os_family == 'RedHat'

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'
