---
- name: Check if cpanm is installed
  shell: which cpanm
  ignore_errors: yes
  register: cpanm_installed
  changed_when: false

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'

- include: "{{role_path}}/tasks/redhat.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- include: "{{role_path}}/tasks/fedora.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Check if sudo is required for cpanm
  shell: cpanm Test::Simple
  ignore_errors: yes
  register: cpanm_requires_sudo
  changed_when: false

- debug:
    var: cpanm_requires_sudo
