---
- name: Check if plenv and cpanm are installed
  shell: ~/.plenv/bin/plenv which cpanm
  ignore_errors: yes
  register: cpanm_installed
  become: yes
  become_user: "{{ app_user_internal }}"
  changed_when: false

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'

- include: "{{role_path}}/tasks/redhat.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- include: "{{role_path}}/tasks/fedora.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Check if DBD::Oracle is installed
  shell: ~/.plenv/bin/plenv exec perl -MDBD::Oracle -E 'say 1'
  ignore_errors: yes
  register: dbd_oracle_installed
  become: yes
  become_user: "{{ app_user_internal }}"
  changed_when: false

- name: Find oracle_home
  shell: ~/.plenv/bin/plenv exec perl -MFile::Find -E 'my $t={};find(sub {my $d = $File::Find::dir;$t->{$d} = "$1\n" if $d =~ m!(.*/oracle/.*)/bin$!; END: print values %$t}, "/")'
  ignore_errors: yes
  register: find_oracle_home
  become: yes
  become_user: "{{ app_user_internal }}"
  changed_when: false

- name: Find oracle_lib
  shell: ~/.plenv/bin/plenv exec perl -MFile::Find -E 'my $t={};find(sub {my $d = $File::Find::dir;$t->{$d} = "$1\n" if $d =~ m!(.*/oracle/.*/lib)$!; END: print values %$t}, "/")'
  ignore_errors: yes
  register: find_oracle_lib
  become: yes
  become_user: "{{ app_user_internal }}"
  changed_when: false

- debug:
    var: dbd_oracle_installed

- debug:
    var: find_oracle_home

- debug:
    var: find_oracle_lib

- name: Installs DBD::Oracle
  shell:
    cmd: |
      cd
      ~/.plenv/bin/plenv exec cpanm DBI
      ~/.plenv/bin/plenv exec cpanm --look DBD::Oracle <<FINAL
      perl Makefile.PL -l
      make
      make test
      make install
      exit
      FINAL
  become: yes
  become_user: "{{ app_user_internal }}"
  environment:
    - ORACLE_HOME: "{{ find_oracle_home.stdout }}"
    - LD_LIBRARY_PATH: "{{ find_oracle_lib.stdout }}"
  when: dbd_oracle_installed.stdout != '1'
  