---
- name: Check if cpanm is installed
  shell: which cpanm
  ignore_errors: yes
  register: cpanm_installed
  changed_when: false

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'

- include: "{{role_path}}/tasks/redhat.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- include: "{{role_path}}/tasks/fedora.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Check if sudo is required for cpanm
  shell: cpanm Test::Simple
  ignore_errors: yes
  register: cpanm_requires_sudo
  changed_when: false

- debug:
    var: cpanm_requires_sudo

- expect:
    command: cpanm DBI Term::ReadKey Term::ReadLine::Perl
    responses:
      "":""
  become: yes

- expect:
    command: cpanm --look DBD::Oracle
    responses:
      "": perl Makefile.PL -l
      "": make
      "": make test
      "": make install
      "": exit
  become: yes
  environment:
    - ORACLE_HOME: /usr/lib/oracle/12.1/client64
    - LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
