---
- name: Check if cpanm is installed
  shell: which cpanm
  ignore_errors: yes
  register: cpanm_installed
  changed_when: false

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'

- include: "{{role_path}}/tasks/redhat.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- include: "{{role_path}}/tasks/fedora.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Check if sudo is required for cpanm
  shell: cpanm Test::Simple
  ignore_errors: yes
  register: cpanm_requires_sudo
  changed_when: false

- debug:
    var: cpanm_requires_sudo

- name: Installs several prerequisites
  shell:
    cmd: |
      cpanm DBI Term::ReadKey Term::ReadLine::Perl <<EOF
      exit
      EOF
  become: yes
  ignore_errors: yes

- name: Installs DBD::Oracle
  shell:
    cmd: |
      cpanm --look DBD::Oracle <<FINAL
      perl Makefile.PL -l
      make
      make test
      make install
      exit
      FINAL
  become: yes
  environment:
    - ORACLE_HOME: /usr/lib/oracle/12.1/client64
    - LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
  ignore_errors: yes
