---
- find:
    paths: "{{ role_path }}/files/oracle"
    patterns: "*.rpm"
  register: oracle_rpms

- name: Installs rpms, RedHar except Fedora
  when: ansible_distribution != 'Fedora'
  yum:
    name:  "{{ item.path }}"
    state: present
  with_items: "{{ oracle_rpms.files  | sort(attribute='path') }}"
  