---
- find:
    paths: "{{ role_path }}/files/oracle"
    patterns: "*.rpm"
  register: oracle_rpms

- name: Installs rpms
  yum:
    name:  "{{ item }}"
    state: present
  with_items: "{{ oracle_rpms.files  | sort(attribute='path') | map(attribute='path') | list }}"