---
- find:
    paths: "{{ role_path }}/files/oracle"
    patterns: "*.rpm"
  register: oracle_rpms

- name: Installs rpms, RedHar except Fedora
  when: ansible_distribution != 'Fedora'
  yum:
    name:  "{{ item.path }}"
    state: present
  with_items: "{{ oracle_rpms.files  | sort(attribute='path') }}"

- name: Installs cpanm prerequisites
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - perl-devel
    - perl-CPAN
  when: cpanm_installed.stdout == '' and ansible_distribution_major_version == "6"

- name: Installs cpanm
  shell: "curl -L https://cpanmin.us | perl - App::cpanminus"
  become: yes
  when: cpanm_installed.stdout == '' and ansible_distribution_major_version == "6"

- name: Installs cpanm on major version 7
  yum: name=perl-App-cpanminus state=present update_cache=yes
  when: cpanm_installed.stdout == '' and ansible_distribution_major_version == "7"
